server:
  port: 7071

mybatis:
  configLocation: classpath:mybatis/config.xml
  mapperLocations: classpath:mybatis/mapper/*.xml
  typeAliasesPackage: com.service.base.entity
  
spring:
  datasource:
    url: jdbc:mysql://192.168.9.60:3306/sms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 19a8f11b83
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource